### ISSUE TITLE
[deploy] Setup grafana

### ISSUE THREAD

**Issue by corpix** [cryptounicorns/docs#12]
Atm blocked by https://github.com/cryptounicorns/docs/issues/11

**Comment by olegakbarov** [comment]
Did some initial work in `greed/prometheus-local`

**Comment by narkq** [comment]
Grafana is deployed, but no data source provisioning yet (i.e. requires manual fiddling).

**Comment by corpix** [comment]
I don't think we could provide data sources easily at this moment(but it could be a cool think to support in nix module for grafana). I could create a backlog issue about data source provisioning so we could close this. Is it ok?

**Comment by narkq** [comment]
Yep, I think it's fine as long as we keep making backups of grafana database.

-----Original Message-----
