### ISSUE TITLE
[mammoth] Fix crash with small resolution

### ISSUE THREAD

**Issue by olegakbarov** [cryptounicorns/docs#3]
[Check this] Influx crashes when interval too long

**Comment by corpix** [comment]
Yeah it crashes if resolution is too small which results in influxdb high memory consumption(OOM killer is the issue).
I think the possible way to fix it is to:
- restrict the resolution to be > 1hour
- set limit in sql query

Probably influxdb could be patched in a way so it will use constant memory to prepare data but I am not sure this is possible.

**Comment by olegakbarov** [comment]
Restrict resolution should be fine, i guess. Let Influx guys know about issue is good idea as well.

**Comment by corpix** [comment]
Yeah, I will need to collect some metrics before I get in touch with them but this seems unnecessary if we will move to clickhouse :)

**Comment by olegakbarov** [comment]
Shall we?

**Comment by corpix** [comment]
After I have discovered the way they do commerce... probably I don't want to waste my time on this, we could just try to move to clickhouse.

**Comment by olegakbarov** [comment]
I'm afraid soon we'll be out of db's to migrate to 😅

**Comment by corpix** [comment]
Restricted resolution on the config level in mammoth https://github.com/cryptounicorns/mammoth/blob/0c32ca3c7cbe7d5ad3d411386be525c2f1d38ac3/config.nix#L100
