### ISSUE TITLE
[desktop] Can't pick other currency pair if chart is open

### ISSUE THREAD

**Issue by corpix** [cryptounicorns/docs#31]
Steps to reproduce:
- open best price or favorites
- click on some currency pair, chart will open
- click on other currency pair, nothing happens

Expected behaviour:
- open best price or favorites
- click on some(btc-usd) currency pair, chart(btc-usd) will open
- click on other(eos-usd) currency pair, chart(eos-usd) will open

**Comment by olegakbarov** [comment]
Done here https://github.com/cryptounicorns/desktop/commit/46ac6b3fd0c814c88a6590089f9816058ebe4e13
