### ISSUE TITLE
[ferret] Changes from greed not propagated to client

### ISSUE THREAD

**Issue by corpix** [cryptounicorns/docs#66]

**Comment by corpix** [comment]
Ok, found ferret service was lack `wantedBy = [ "multi-user.target" ];` :)

**Comment by olegakbarov** [comment]
Shall we close it then @corpix ?

**Comment by corpix** [comment]
No, I have discovered we have no changes for some pairs on `liqui` for some reason, investigating

**Comment by corpix** [comment]
It is working for all pairs after refactoring, awaiting deploy
